#image: node:14.11.0-alpine

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test_stuff:
  image: node:14.11.0-alpine
  stage: test
  script:
   - npm install 
   - npm run-script build
   # TODO: some kinda testy stuff?
  tags:
    - docker

dockerise:
  image: docker:19.03
  stage: build
  before_script: 
    - docker info
  script:
    - docker build -t my-docker-image
    - docker run my-docker-image /bin/echo this is totally a legit test!
  tags:
    - docker


