image: node:14.11.0-alpine

cache:
  paths:
  - node_modules/

stages:
  - test

test_install:
  stage: test
  script:
  # trust the cache --registry http://0.0.0.0:5080
   - npm install 
#--registry http://gitlab.lislan.org.uk:5080
#   - node ./specs/start.js ./specs/async.spec.js
  tags:
    - docker

