#image: node:14.11.0-alpine
#
#variables:
#  DOCKER_DRIVER: overlay2
#  #  DOCKER_HOST: tcp://localhost:2375

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test_stuff:
  image: node:14.11-alpine
  stage: test
  script:
   - npm install 
   - npm run-script build
   # TODO: some kinda testy stuff?
  tags:
    - docker

build-docker:
  image: docker:19.03
  #image: curlimages/curl
  stage: build
  before_script: 
    - docker info
    #    - echo $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD | cat
    #- curl https://registry.lislan.org.uk:5050/v2/
    - docker login registry.lislan.org.uk:5050 -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image /bin/echo this is totally a legit test!
    - docker push ld47/deploy:latest
  tags:
    - docker



